version: "3.8"
services:
  fraud-service:
    build:
      context: .
      dockerfile: services/fraud-service/Dockerfile
    image: fraud-service:latest
    ports:
      - "8081:8080" # host:container
    restart: unless-stopped

  transaction-service:
    build:
      context: .
      dockerfile: services/transaction-service/Dockerfile
    image: transaction-service:latest
    ports:
      - "8082:8080"
    environment:
      - FRAUD_SERVICE_URL=http://fraud-service:8080/predict
      - FRAUD_THRESHOLD=0.5
    depends_on:
      - fraud-service
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    image: api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - TRANSACTION_SERVICE_URL=http://transaction-service:8080/transaction
    depends_on:
      - transaction-service
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    depends_on:
      - api-gateway
      - transaction-service
      - fraud-service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  grafana-storage:
